config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end

  resources :charges, only: [:new, :create]

  devise_for :users
  
  get 'downgrade' => 'users#downgrade'
   
  root to: 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :wiki
  
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :wikis 

  after_initialize :set_role

  def admin?
    role == 'admin'
  end
 
  def premium?
    role == 'premium'
  end

  def set_role
    self.role  ||= 'standard'   
  end        

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :visible_to, -> (user) { user && ((user.role == 'premium') || (user.role == 'admin')) ? all : where((private == false) || (private == nil))  }

  def collaborator_for(user)
    collaborators.where(user: user).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

    rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

protected

  def after_sign_in_path_for(resource)
    wikis_path
  end
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController 
 def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Premium Membership - #{current_user.name}",
     amount: 15_00
   }
 end

 def create

   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   charge = Stripe::Charge.create(
     customer: customer.id, 
     amount: 15_00,
     description: "Premium Membership - #{current_user.email}",
     currency: 'usd'
   )

   current_user.update_attribute(:role, 'premium')

   flash[:success] = "Congratulations, #{current_user.email}! Enjoy your new Premium membership."
   redirect_to root_path 
 
 rescue Stripe::CardError => e
   flash[:error] = e.message
   redirect_to new_charge_path
 end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController 
  before_action :set_wiki

  def create
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])
    if @collaborator.save
      flash[:notice] = "Your wiki was updated."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error updating your wiki. Please try again."
      render :new
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    if @collaborator.destroy
      flash[:notice] = "Wiki was sucessfully updated."
      redirect_to edit_wiki_path(@wiki)
    else
      flash[:error] = "There was an error. Please try again."
      render :show
    end
  end

private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def downgrade 
    current_user.update_attribute(:role, 'standard')
    
    current_user.wikis.each do |wiki|
      wiki.update_attribute(:private, false)
    end
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :role)
  end

  def wiki_params(wiki)
    params.require(:wiki).permit(:private)
  end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Your wiki was saved."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving your wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was sucessfully updated."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
      flash[:notice] = "Wiki was sucessfully deleted."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error deleting the wiki. Please try again."
      render :show
    end
  end

  private

    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<% unless current_user.premium? %> 
 <%= form_tag charges_path do %>
   <h1>Upgrade to Premium!</h1>
 </br>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

<% else %>
<h2>Downgrade Account</h2>
<h4><br>Are you sure you want to lose premium acccess to Blocipedia? <br><br>If you downgrade your account, your private wikis will become public.
</h4>
<br>
<%= link_to "Yes, downgrade my account", downgrade_path, class: 'btn btn-warning', data: { confirm: 'Are you sure you want to downgrade and make all your wikis public?' } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, intial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
   <ul class ="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>


         <div class="pull-right user-info">
           <% if current_user  %>
              Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! | 

              <% if current_user.role == 'standard' %>
                <%= link_to "Upgrade to Premium", new_charge_path %> |
              <% end %>
              
              <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                          
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
         
   </ul>

   <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

<%= yield %>

  </div>
</body>
</html>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Blocipedia</h1>
  <p>Create your own wikis with Blocipedia</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

app/views/wikis/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Wiki Rules:</p>
    <ol>
      <li>Make it useful</li>
      <li>Cite sources where needed</li>
      <li>Check your puncuation</li>
    </ol>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
       <% if current_user.role == 'admin' || current_user.role == 'premium' %>
       <div class="form-group">
         <%= f.label :private, class: 'checkbox' do %>
         <%= f.check_box :private %> Private wiki
         <% end %>

       </div>
       <% end %>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 
   <%= render partial: 'form', locals: { wiki: @wiki } %>

<% if current_user.premium? || current_user.admin? %>
<h3>Manage Collaborators</h3>

<table class = 'table'>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td>
      <% if @wiki.users.include? user %>
      <%= link_to "Remove Collaborator", wiki_collaborator_path(@wiki, @wiki.collaborator_for(user)), method: :delete, class: 'btn btn-danger' %>
      <% else %>
      <%= link_to "Add Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-success' %>
      <% end %>
    </td>  
  </tr>
  <% end %>

</table>

<% end %>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<% if policy(Wiki.new).create? %>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% end %>

<% @wikis.each do |wiki| %>
  <% if policy(wiki).show? %>
    <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
       </h4>
     </div>
   </div>
  <% end %>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
     
  <%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

<% if policy(@wiki).edit? %>
 <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>

 <% if policy(@wiki).destroy? %>      
  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> 
<% end %>

<p><%= markdown_to_html @wiki.body %></p>